name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: Install dependencies for linting documents
        run: python3 -m pip install docutils pygments
      - name: Lint restructuredtext.rst
        run: rst2pseudoxml.py --config=docutils.conf restructuredtext/restructuredtext.rst /dev/null
