name: "CI"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v1"
      - uses: "actions/setup-python@v1"
      - name: "Install dependencies for linting documents"
        run: "python3 -m pip install docutils pygments"
      - name: "Lint documents"
        run: |
          find . -type f -name "*.rst" -print0 | xargs --max-lines=1 --null rst2pseudoxml.py --config=docutils.conf > /dev/null
